"""make transport refrigeration nullable

Revision ID: 27a920326238
Revises: afba5c616618
Create Date: 2026-08-25 11:12:40.617167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a920326238'
down_revision: Union[str, Sequence[str], None] = 'afba5c616618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pnc_transport', 'has_refrigeration',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "UPDATE pnc_transport "
            "SET has_refrigeration = FALSE "
            "WHERE has_refrigeration IS NULL"
        )
    )
    op.alter_column('pnc_transport', 'has_refrigeration',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
