"""create QualityCapability entity

Revision ID: 2d7ecc630545
Revises: 6e6707e23e1a
Create Date: 2026-08-03 16:48:10.146692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7ecc630545'
down_revision: Union[str, Sequence[str], None] = '6e6707e23e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_quality_capability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('min_it_grade', sa.Integer(), nullable=True),
    sa.Column('min_ra', sa.Float(), nullable=True),
    sa.Column('measuring_tools', sa.Boolean(), nullable=False),
    sa.Column('cim_machine', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pnc_quality_capability')
    # ### end Alembic commands ###
