"""align lifting equipment and order indexes

Revision ID: 31ff9146c39c
Revises: a3ca9b6c64bb
Create Date: 2026-08-14 12:13:18.454373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ff9146c39c'
down_revision: Union[str, Sequence[str], None] = 'a3ca9b6c64bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pnc_lifting_facility_id'), table_name='pnc_lifting_equipment')
    op.drop_index(op.f('ix_pnc_lifting_load_capacity'), table_name='pnc_lifting_equipment')
    op.drop_index(op.f('ix_pnc_lifting_profile_type'), table_name='pnc_lifting_equipment')
    op.drop_index(op.f('ix_pnc_lifting_warehouse_id'), table_name='pnc_lifting_equipment')
    op.create_index('ix_pnc_lifting_equipment_facility_id', 'pnc_lifting_equipment', ['facility_id'], unique=False)
    op.create_index('ix_pnc_lifting_equipment_load_capacity', 'pnc_lifting_equipment', ['load_capacity_tons'], unique=False)
    op.create_index('ix_pnc_lifting_equipment_profile_type', 'pnc_lifting_equipment', ['profile_id', 'crane_type_code'], unique=False)
    op.create_index('ix_pnc_lifting_equipment_warehouse_id', 'pnc_lifting_equipment', ['warehouse_id'], unique=False)
    op.create_index('ix_pnc_order_deadline', 'pnc_production_order', ['deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_order_deadline', table_name='pnc_production_order')
    op.drop_index('ix_pnc_lifting_equipment_warehouse_id', table_name='pnc_lifting_equipment')
    op.drop_index('ix_pnc_lifting_equipment_profile_type', table_name='pnc_lifting_equipment')
    op.drop_index('ix_pnc_lifting_equipment_load_capacity', table_name='pnc_lifting_equipment')
    op.drop_index('ix_pnc_lifting_equipment_facility_id', table_name='pnc_lifting_equipment')
    op.create_index(op.f('ix_pnc_lifting_warehouse_id'), 'pnc_lifting_equipment', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_pnc_lifting_profile_type'), 'pnc_lifting_equipment', ['profile_id', 'crane_type_code'], unique=False)
    op.create_index(op.f('ix_pnc_lifting_load_capacity'), 'pnc_lifting_equipment', ['load_capacity_tons'], unique=False)
    op.create_index(op.f('ix_pnc_lifting_facility_id'), 'pnc_lifting_equipment', ['facility_id'], unique=False)
    # ### end Alembic commands ###
