"""create warehouse and lifting equipment entities

Revision ID: 360dbb4023c5
Revises: cc38d3d12d57
Create Date: 2026-07-31 16:30:00.625326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360dbb4023c5'
down_revision: Union[str, Sequence[str], None] = 'cc38d3d12d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_warehouse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_type_code', sa.String(length=50), nullable=False),
    sa.Column('total_capacity_cube', sa.Float(), nullable=False),
    sa.Column('max_load_sqm', sa.Float(), nullable=True),
    sa.Column('temperature_control', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.ForeignKeyConstraint(['warehouse_type_code'], ['pnc_warehouse_type.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pnc_warehouse_profile_type', 'pnc_warehouse', ['profile_id', 'warehouse_type_code'], unique=False)
    op.create_table('pnc_lifting_equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('crane_type_code', sa.String(length=50), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('load_capacity_tons', sa.Float(), nullable=False),
    sa.Column('max_lift_height', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crane_type_code'], ['pnc_crane_type.code'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['pnc_production_facility.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['pnc_warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pnc_lifting_facility_id', 'pnc_lifting_equipment', ['facility_id'], unique=False)
    op.create_index('ix_pnc_lifting_load_capacity', 'pnc_lifting_equipment', ['load_capacity_tons'], unique=False)
    op.create_index('ix_pnc_lifting_profile_type', 'pnc_lifting_equipment', ['profile_id', 'crane_type_code'], unique=False)
    op.create_index('ix_pnc_lifting_warehouse_id', 'pnc_lifting_equipment', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_lifting_warehouse_id', table_name='pnc_lifting_equipment')
    op.drop_index('ix_pnc_lifting_profile_type', table_name='pnc_lifting_equipment')
    op.drop_index('ix_pnc_lifting_load_capacity', table_name='pnc_lifting_equipment')
    op.drop_index('ix_pnc_lifting_facility_id', table_name='pnc_lifting_equipment')
    op.drop_table('pnc_lifting_equipment')
    op.drop_index('ix_pnc_warehouse_profile_type', table_name='pnc_warehouse')
    op.drop_table('pnc_warehouse')
    # ### end Alembic commands ###
