"""create TransportOwnershipType reference

Revision ID: 3d3011ca9f01
Revises: e7b89aa4adf8
Create Date: 2026-07-30 15:41:29.839085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3011ca9f01'
down_revision: Union[str, Sequence[str], None] = 'e7b89aa4adf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_transport_ownership_type',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('ics_section', sa.String(length=50), nullable=True),
    sa.Column('ref_system', sa.String(length=100), nullable=False),
    sa.Column('ref_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pnc_transport_ownership_type')
    # ### end Alembic commands ###
