"""create Certificate type reference

Revision ID: 4c8d2348c65e
Revises: 7d6fda9f7669
Create Date: 2026-07-30 12:34:26.273938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8d2348c65e'
down_revision: Union[str, Sequence[str], None] = '7d6fda9f7669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_certificate_type',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('ics_section', sa.String(length=50), nullable=True),
    sa.Column('ref_system', sa.String(length=100), nullable=False),
    sa.Column('ref_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pnc_certificate_type')
    # ### end Alembic commands ###
