"""create Material and MaterialItem entities

Revision ID: 5242a0facf88
Revises: 736be97db8ec
Create Date: 2026-08-03 10:24:01.883973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5242a0facf88'
down_revision: Union[str, Sequence[str], None] = '736be97db8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_code', sa.String(length=50), nullable=False),
    sa.Column('grade_name', sa.String(length=100), nullable=False),
    sa.Column('density', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['group_code'], ['pnc_material_group.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code', 'grade_name', name='uq_pnc_material_group_grade')
    )
    op.create_index('ix_pnc_material_grade_name', 'pnc_material', ['grade_name'], unique=False)
    op.create_index('ix_pnc_material_group_code', 'pnc_material', ['group_code'], unique=False)
    op.create_table('pnc_material_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('material_form_code', sa.String(length=50), nullable=False),
    sa.Column('dimension_1', sa.Float(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['material_form_code'], ['pnc_material_form.code'], ),
    sa.ForeignKeyConstraint(['material_id'], ['pnc_material.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'material_form_code', 'dimension_1', 'unit_of_measure', name='uq_pnc_material_item_form_dimension_unit')
    )
    op.create_index('ix_pnc_material_item_material_form', 'pnc_material_item', ['material_id', 'material_form_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_material_item_material_form', table_name='pnc_material_item')
    op.drop_table('pnc_material_item')
    op.drop_index('ix_pnc_material_group_code', table_name='pnc_material')
    op.drop_index('ix_pnc_material_grade_name', table_name='pnc_material')
    op.drop_table('pnc_material')
    # ### end Alembic commands ###
