"""create EnterpriseIndustry entity

Revision ID: 6e6707e23e1a
Revises: 9c4718dcee71
Create Date: 2026-08-03 16:24:07.783790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6707e23e1a'
down_revision: Union[str, Sequence[str], None] = '9c4718dcee71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_enterprise_industry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['industry_code'], ['pnc_industry.code'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'industry_code', name='uq_pnc_enterprise_industry_profile_industry')
    )
    op.create_index('ix_pnc_enterprise_industry_primary', 'pnc_enterprise_industry', ['profile_id'], unique=True, postgresql_where=sa.text('is_primary IS TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_enterprise_industry_primary', table_name='pnc_enterprise_industry', postgresql_where=sa.text('is_primary IS TRUE'))
    op.drop_table('pnc_enterprise_industry')
    # ### end Alembic commands ###
