"""create Transport entity

Revision ID: 736be97db8ec
Revises: 360dbb4023c5
Create Date: 2026-07-31 22:45:21.857055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736be97db8ec'
down_revision: Union[str, Sequence[str], None] = '360dbb4023c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_transport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('transport_type_code', sa.String(length=50), nullable=False),
    sa.Column('transport_scope_code', sa.String(length=50), nullable=False),
    sa.Column('transport_ownership_code', sa.String(length=50), nullable=False),
    sa.Column('payload_tons', sa.Float(), nullable=False),
    sa.Column('body_volume_cube', sa.Float(), nullable=True),
    sa.Column('has_refrigeration', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.ForeignKeyConstraint(['transport_ownership_code'], ['pnc_transport_ownership_type.code'], ),
    sa.ForeignKeyConstraint(['transport_scope_code'], ['pnc_transport_scope.code'], ),
    sa.ForeignKeyConstraint(['transport_type_code'], ['pnc_transport_type.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pnc_transport_profile_scope', 'pnc_transport', ['profile_id', 'transport_scope_code'], unique=False)
    op.create_index('ix_pnc_transport_profile_type', 'pnc_transport', ['profile_id', 'transport_type_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_transport_profile_type', table_name='pnc_transport')
    op.drop_index('ix_pnc_transport_profile_scope', table_name='pnc_transport')
    op.drop_table('pnc_transport')
    # ### end Alembic commands ###
