"""create product type reference

Revision ID: 88fd91547c79
Revises: 10b78cde39ca
Create Date: 2026-07-30 10:55:35.765649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fd91547c79'
down_revision: Union[str, Sequence[str], None] = '10b78cde39ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_product_type',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('ics_section', sa.String(length=50), nullable=True),
    sa.Column('ref_system', sa.String(length=100), nullable=False),
    sa.Column('ref_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pnc_product_type')
    # ### end Alembic commands ###
