"""create EnterpriseProfile entity

Revision ID: 96fcce522037
Revises: 563aa6066377
Create Date: 2026-07-30 16:45:35.176129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fcce522037'
down_revision: Union[str, Sequence[str], None] = '563aa6066377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_enterprise_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('employees_count', sa.Integer(), nullable=True),
    sa.Column('company_size_code', sa.String(length=50), nullable=True),
    sa.Column('region_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['company_size_code'], ['pnc_company_size.code'], ),
    sa.ForeignKeyConstraint(['region_code'], ['pnc_region.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn', name='uq_pnc_enterprise_profile_inn'),
    sa.UniqueConstraint('ogrn', name='uq_pnc_enterprise_profile_ogrn')
    )
    op.create_index('ix_pnc_enterprise_profile_company_name', 'pnc_enterprise_profile', ['company_name'], unique=False)
    op.create_index('ix_pnc_enterprise_profile_company_size_code', 'pnc_enterprise_profile', ['company_size_code'], unique=False)
    op.create_index('ix_pnc_enterprise_profile_region_code', 'pnc_enterprise_profile', ['region_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_enterprise_profile_region_code', table_name='pnc_enterprise_profile')
    op.drop_index('ix_pnc_enterprise_profile_company_size_code', table_name='pnc_enterprise_profile')
    op.drop_index('ix_pnc_enterprise_profile_company_name', table_name='pnc_enterprise_profile')
    op.drop_table('pnc_enterprise_profile')
    # ### end Alembic commands ###
