"""create EnterpriseCertificate entity

Revision ID: 9c4718dcee71
Revises: d88904506af1
Create Date: 2026-08-03 15:00:22.220536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4718dcee71'
down_revision: Union[str, Sequence[str], None] = 'd88904506af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_enterprise_certificate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('certificate_type_code', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_type_code'], ['pnc_certificate_type.code'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'certificate_type_code', 'issue_date', 'expiry_date', name='uq_pnc_certificate_profile_type_dates')
    )
    op.create_index('ix_pnc_certificate_expiry_date', 'pnc_enterprise_certificate', ['expiry_date'], unique=False)
    op.create_index('ix_pnc_certificate_profile_type_expiry', 'pnc_enterprise_certificate', ['profile_id', 'certificate_type_code', 'expiry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_certificate_profile_type_expiry', table_name='pnc_enterprise_certificate')
    op.drop_index('ix_pnc_certificate_expiry_date', table_name='pnc_enterprise_certificate')
    op.drop_table('pnc_enterprise_certificate')
    # ### end Alembic commands ###
