"""add okved tables

Revision ID: a3ca9b6c64bb
Revises: 2d7ecc630545
Create Date: 2026-08-12 17:00:42.597917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ca9b6c64bb'
down_revision: Union[str, Sequence[str], None] = '2d7ecc630545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_okved',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_ru', sa.String(length=500), nullable=False),
    sa.Column('parent_code', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_code'], ['pnc_okved.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_pnc_okved_parent_code', 'pnc_okved', ['parent_code'], unique=False)
    op.create_table('pnc_enterprise_okved',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('okved_code', sa.String(length=10), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['okved_code'], ['pnc_okved.code'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'okved_code', name='uq_enterprise_okved')
    )
    op.create_index('ix_pnc_enterprise_okved_code', 'pnc_enterprise_okved', ['okved_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_enterprise_okved_code', table_name='pnc_enterprise_okved')
    op.drop_table('pnc_enterprise_okved')
    op.drop_index('ix_pnc_okved_parent_code', table_name='pnc_okved')
    op.drop_table('pnc_okved')
    # ### end Alembic commands ###
