"""add model name to equipment

Revision ID: afba5c616618
Revises: 31ff9146c39c
Create Date: 2026-08-20 17:19:36.830892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afba5c616618'
down_revision: Union[str, Sequence[str], None] = '31ff9146c39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pnc_equipment', sa.Column('model_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pnc_equipment', 'model_name')
    # ### end Alembic commands ###
