"""create Equipment entity

Revision ID: cc38d3d12d57
Revises: f4222c93ead1
Create Date: 2026-07-31 11:48:31.096143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc38d3d12d57'
down_revision: Union[str, Sequence[str], None] = 'f4222c93ead1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_code', sa.String(length=50), nullable=False),
    sa.Column('cnc', sa.Boolean(), nullable=False),
    sa.Column('axes', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('max_diameter', sa.Float(), nullable=True),
    sa.Column('working_zone_x', sa.Float(), nullable=True),
    sa.Column('working_zone_y', sa.Float(), nullable=True),
    sa.Column('working_zone_z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_type_code'], ['pnc_equipment_type.code'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['pnc_production_facility.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pnc_equipment_facility_type', 'pnc_equipment', ['facility_id', 'equipment_type_code'], unique=False)
    op.create_index('ix_pnc_equipment_profile_type', 'pnc_equipment', ['profile_id', 'equipment_type_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_equipment_profile_type', table_name='pnc_equipment')
    op.drop_index('ix_pnc_equipment_facility_type', table_name='pnc_equipment')
    op.drop_table('pnc_equipment')
    # ### end Alembic commands ###
