"""create ProductionOrder entity

Revision ID: d88904506af1
Revises: e6c8e0c6e883
Create Date: 2026-08-03 14:31:52.184877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88904506af1'
down_revision: Union[str, Sequence[str], None] = 'e6c8e0c6e883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_production_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('order_type_code', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.String(length=50), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['industry_code'], ['pnc_industry.code'], ),
    sa.ForeignKeyConstraint(['order_type_code'], ['pnc_order_type.code'], ),
    sa.ForeignKeyConstraint(['product_id'], ['pnc_product.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'order_number', name='uq_pnc_order_profile_number')
    )
    op.create_index('ix_pnc_order_industry_deadline', 'pnc_production_order', ['industry_code', 'deadline'], unique=False)
    op.create_index('ix_pnc_order_product_id', 'pnc_production_order', ['product_id'], unique=False)
    op.create_index('ix_pnc_order_profile_deadline', 'pnc_production_order', ['profile_id', 'deadline'], unique=False)
    op.create_index('ix_pnc_order_type_deadline', 'pnc_production_order', ['order_type_code', 'deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_order_type_deadline', table_name='pnc_production_order')
    op.drop_index('ix_pnc_order_profile_deadline', table_name='pnc_production_order')
    op.drop_index('ix_pnc_order_product_id', table_name='pnc_production_order')
    op.drop_index('ix_pnc_order_industry_deadline', table_name='pnc_production_order')
    op.drop_table('pnc_production_order')
    # ### end Alembic commands ###
