"""create Industry reference

Revision ID: db92cb56ea5f
Revises: 4c8d2348c65e
Create Date: 2026-07-30 12:41:05.602946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db92cb56ea5f'
down_revision: Union[str, Sequence[str], None] = '4c8d2348c65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_industry',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('ics_section', sa.String(length=50), nullable=True),
    sa.Column('ref_system', sa.String(length=100), nullable=False),
    sa.Column('ref_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pnc_industry')
    # ### end Alembic commands ###
