"""create Product entity

Revision ID: e6c8e0c6e883
Revises: 5242a0facf88
Create Date: 2026-08-03 12:32:31.681410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c8e0c6e883'
down_revision: Union[str, Sequence[str], None] = '5242a0facf88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('product_type_code', sa.String(length=50), nullable=False),
    sa.Column('material_item_id', sa.Integer(), nullable=False),
    sa.Column('sku_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weight_net', sa.Float(), nullable=False),
    sa.Column('required_it_grade', sa.Integer(), nullable=True),
    sa.Column('required_ra', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_item_id'], ['pnc_material_item.id'], ),
    sa.ForeignKeyConstraint(['product_type_code'], ['pnc_product_type.code'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'sku_code', name='uq_pnc_product_profile_sku')
    )
    op.create_index('ix_pnc_product_material_item_id', 'pnc_product', ['material_item_id'], unique=False)
    op.create_index('ix_pnc_product_name', 'pnc_product', ['name'], unique=False)
    op.create_index('ix_pnc_product_profile_type', 'pnc_product', ['profile_id', 'product_type_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_product_profile_type', table_name='pnc_product')
    op.drop_index('ix_pnc_product_name', table_name='pnc_product')
    op.drop_index('ix_pnc_product_material_item_id', table_name='pnc_product')
    op.drop_table('pnc_product')
    # ### end Alembic commands ###
