"""create ProductionFacility entity

Revision ID: f4222c93ead1
Revises: 96fcce522037
Create Date: 2026-07-30 17:13:59.564286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4222c93ead1'
down_revision: Union[str, Sequence[str], None] = '96fcce522037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnc_production_facility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('available_area', sa.Float(), nullable=False),
    sa.Column('power_capacity', sa.Float(), nullable=True),
    sa.Column('gas_supply', sa.Boolean(), nullable=False),
    sa.Column('compressed_air', sa.Boolean(), nullable=False),
    sa.Column('water_supply', sa.Boolean(), nullable=False),
    sa.Column('steam_supply', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['pnc_enterprise_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'facility_name', name='uq_pnc_production_facility_profile_name')
    )
    op.create_index('ix_pnc_production_facility_profile_id', 'pnc_production_facility', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pnc_production_facility_profile_id', table_name='pnc_production_facility')
    op.drop_table('pnc_production_facility')
    # ### end Alembic commands ###
